_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNFewShot"
  WEIGHTS: "manifold://fai4ar/tree/liyin/few-shot/baselinesbase/20210126214118/e2e_train/randinit/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ("coco_trainval_all_10shot",)
  TEST: ("coco_test_all",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (144000,)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 10
OUTPUT_DIR: "manifold://fai4ar/tree/liyin/few-shot/baselines/finetune_all"
