_BASE_: "Base-Meta-FCOS-finetune.yaml"
MODEL:
  WEIGHTS: "manifold://fai4ar/tree/liyin/few-shot/meta-fcos/test/20210622175503/e2e_train/model_0014999.pth"
  # LVIS final: f281383683, 20210622175503
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "output/fcos/R_50_1x"
