MODEL:
  META_ARCHITECTURE: "MetaOneStageDetector"
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    # NORM: "GN"
  PROPOSAL_GENERATOR:
    NAME: "MetaFCOS"
    OWD: False
  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]

  META_LEARN:
    EPISODIC_LEARNING: False # pretraining
  FCOS:
    NUM_CLASSES: 1104 #703 #405
    POST_NMS_TOPK_TEST: 300 # increase from 100
    POST_NMS_TOPK_TRAIN: 300
    NUM_CLS_CONVS: 4
    CLS_LOGITS_KERNEL_SIZE: 1
    NORM: "GN" # default
    # The following configs is added into OWD research
    BOX_QUALITY: ["ctrness"]
    CENTER_SAMPLE: True
    IOU_MASK: False
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
